### ISSUE TITLE
Update naming

### ISSUE THREAD

**Issue by jjw24** [Zeroto521/Wox.Plugin.PythonTemplate#1]
hey @Zeroto521, lets update the naming to Flow.Launcher :)

**Comment by Zeroto521** [comment]
Actually, it is.

I will create a branch for Wox to save the current version.

After creating the wox branch, I will test the Flow.Launcher.Plugin.PythonTemplate, and let it suits for Flow.

**Comment by Zeroto521** [comment]
Some words not about the theme.

I have set some flags/aims as blow.

> 1. database
> 1. auto commands
> 1. local language
> 1. inputs parser, for mulity inputs
> 1. setting ui for wox

- `database` is too weight for Flow / Wox, so I deleted this.
-  `inputs parser` may find a better to solve this problem. And also add to **wox** branch.
- ` setting ui for wox` very likely can't finish for Wox [jjw24/Wox#178](https://github.com/jjw24/Wox/issues/178). But a iead may solve this for Flow, see [#159](https://github.com/Flow-Launcher/Flow.Launcher/issues/159).

**Comment by Zeroto521** [comment]
It seemed that I have no right to create a branch in [Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate).

I need @jjw24 your help to create a `wox` branch in this project.
Then I can PR for the different branches.

**Comment by jjw24** [comment]
> It seemed that I have no right to create a branch in [Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate).
> 
> I need @jjw24 your help to create a `wox` branch in this project.
> Then I can PR for the different branches.

Sorry for the delay. Try now. For some reason you were also in there with 'Read' access so I suspect that's the cause.

Let me know if the access is sufficient as well.

**Comment by Zeroto521** [comment]
:)
No problem, right now.
